"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { fetchTransactions, type CardTransactionView } from "@/lib/api/transactionsClient";
import { formatVnd } from "@/components/cards/cardTypes";

export default function TransactionsPage() {
  const [rows, setRows] = useState<CardTransactionView[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { void fetchTransactions().then(setRows).catch((e) => setError(e instanceof Error ? e.message : "Không thể tải giao dịch.")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => rows.filter((row) => `${row.note} ${row.transactionDate}`.toLowerCase().includes(query.toLowerCase())), [query, rows]);
  return <main className="cc-page min-h-screen px-4 py-8 md:px-8"><div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-[#00687a]">ACTIVITY</p><h1 className="mt-2 text-3xl font-bold cc-text-primary">Transactions</h1><p className="mt-1 cc-text-muted">Theo dõi toàn bộ chi tiêu và cashback theo thời gian.</p></div><Link href="/cards" className="cc-control rounded-lg px-4 py-2 text-sm font-semibold">← Dashboard</Link></header><section className="cc-section overflow-hidden p-5"><div className="mb-5 flex flex-col gap-3 sm:flex-row"><input aria-label="Tìm giao dịch" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm theo ghi chú hoặc ngày..." className="cc-control flex-1 rounded-lg px-3 py-2.5" /><span className="self-center text-sm font-semibold cc-text-muted">{filtered.length} giao dịch</span></div>{loading ? <p className="py-12 text-center cc-text-muted">Đang tải giao dịch...</p> : error ? <p role="alert" className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p> : filtered.length === 0 ? <p className="py-12 text-center cc-text-muted">Chưa có giao dịch phù hợp.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b"><th className="p-3 text-left">Ngày</th><th className="p-3 text-left">Thẻ</th><th className="p-3 text-left">Ghi chú</th><th className="p-3 text-right">Chi tiêu</th><th className="p-3 text-right">Cashback</th></tr></thead><tbody>{filtered.map((row) => <tr key={row._id} className="border-b"><td className="p-3 font-mono">{row.transactionDate}</td><td className="p-3"><p className="font-semibold">Card {row.userCardId.slice(-6)}</p><p className="text-xs cc-text-muted">Statement {row.statementId.slice(-6)}</p></td><td className="p-3">{row.note || "Không có ghi chú"}</td><td className="p-3 text-right font-semibold">{formatVnd(row.outcomeAmount)}</td><td className="p-3 text-right font-semibold text-emerald-600">{formatVnd(row.derived.expectedCashbackAmount)}</td></tr>)}</tbody></table></div>}</section></div></main>;
}
