"use client";

import { useEffect, useMemo, useState } from "react";
import { listFinancialTransactions, type FinancialTransaction } from "@/lib/api/financeClient";
import { FinanceShell, vnd, typeClass, typeLabel } from "@/components/finance/FinanceShell";
import { AiTransactionModal } from "@/components/finance/AiTransactionModal";

export default function TransactionsPage() {
  const [rows, setRows] = useState<FinancialTransaction[]>([]); const [query, setQuery] = useState(""); const [kind, setKind] = useState("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [showAi, setShowAi] = useState(false);
  useEffect(() => { void listFinancialTransactions().then(setRows).catch((e) => setError(e instanceof Error ? e.message : "Không thể tải giao dịch.")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => rows.filter((row) => (kind === "ALL" || row.accountType === kind) && `${row.note} ${row.transactionDate} ${row.categoryId}`.toLowerCase().includes(query.toLowerCase())), [query, rows, kind]);
  return <><FinanceShell title="Giao dịch" action={<button onClick={() => setShowAi(true)} className="rounded-lg bg-[#087f83] px-4 py-2.5 font-semibold text-white">+ Thêm giao dịch</button>}><section className="cc-section overflow-hidden p-5"><div className="mb-5 flex flex-col gap-3 lg:flex-row"><input aria-label="Tìm giao dịch" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm theo ghi chú, danh mục hoặc ngày..." className="cc-control flex-1 rounded-lg px-3 py-2.5" /><div className="flex gap-2 overflow-x-auto">{["ALL", "DEBIT", "CASH", "E_WALLET", "CREDIT"].map((value) => <button key={value} onClick={() => setKind(value)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${kind === value ? "bg-slate-900 text-white" : "bg-slate-100"}`}>{value === "ALL" ? "Tất cả" : typeLabel[value]}</button>)}</div></div>{loading ? <p className="py-12 text-center cc-text-muted">Đang tải giao dịch...</p> : error ? <p role="alert" className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p> : filtered.length === 0 ? <p className="py-12 text-center cc-text-muted">Chưa có giao dịch phù hợp.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b"><th className="p-3 text-left">Ngày</th><th className="p-3 text-left">Phương thức</th><th className="p-3 text-left">Danh mục</th><th className="p-3 text-left">Ownership</th><th className="p-3 text-right">Số tiền</th><th className="p-3 text-right">Cá nhân</th><th className="p-3 text-right">Phải thu</th><th className="p-3 text-right">Nợ credit</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id} className="border-b"><td className="p-3 font-mono">{row.transactionDate}</td><td className="p-3"><span className={`rounded px-2 py-1 text-xs font-bold ${typeClass[row.accountType]}`}>{typeLabel[row.accountType]}</span></td><td className="p-3">{row.categoryId}<p className="text-xs cc-text-muted">{row.note}</p></td><td className="p-3">{row.ownership === "PAID_FOR_OTHER" ? "Chi hộ" : "Cá nhân"}</td><td className="p-3 text-right font-semibold">{vnd(row.amount)}</td><td className="p-3 text-right">{vnd(row.impact.personalSpending)}</td><td className="p-3 text-right text-orange-600">{vnd(row.impact.outstandingReceivable)}</td><td className="p-3 text-right text-violet-700">{vnd(row.impact.creditDebt)}</td></tr>)}</tbody></table></div>}</section></FinanceShell>{showAi ? <AiTransactionModal onClose={() => setShowAi(false)} /> : null}</>;
}
