import mongoose from "mongoose";
import type { FastifyInstance } from "fastify";
import { ApiError } from "./errors.js";
import { requireAdmin, sessionFromRequest } from "./auth.js";
import type { AuthRepository, AuthUser } from "./auth-repository.js";
import { browserServiceContext } from "./context.js";

const serialize = (user: AuthUser) => ({ id: user.id, email: user.email, role: user.role, workspaceId: user.workspaceId, displayName: user.displayName, active: user.active, lockedAt: user.lockedAt });
const displayName = (value: unknown) => { if (typeof value !== "string") throw new ApiError(400, "INVALID_DISPLAY_NAME", "Tên hiển thị không hợp lệ.", { displayName: "Tên hiển thị phải là chuỗi." }); const normalized = value.trim().replace(/\s+/g, " "); if (normalized.length > 80) throw new ApiError(400, "INVALID_DISPLAY_NAME", "Tên hiển thị không hợp lệ.", { displayName: "Tên hiển thị tối đa 80 ký tự." }); return normalized; };
export const registerUserRoutes = (app: FastifyInstance, users: AuthRepository, secret: string) => {
  app.get("/api/profile", async (request) => { const context = await browserServiceContext(request, secret, users); const user = await users.findUserById(context.userId); if (!user) throw new ApiError(404, "USER_NOT_FOUND", "Không tìm thấy người dùng."); return { user: serialize(user) }; });
  app.patch<{ Body: Record<string, unknown> }>("/api/profile", async (request) => { const session = sessionFromRequest(request, secret); const forbidden = ["role", "workspaceId", "email", "active", "lockedAt"].filter((field) => field in (request.body ?? {})); if (forbidden.length) throw new ApiError(403, "FORBIDDEN_PROFILE_FIELD", "Bạn không có quyền cập nhật field này.", { fields: forbidden.join(", ") }); if (!("displayName" in (request.body ?? {}))) throw new ApiError(400, "INVALID_REQUEST", "Không có field hồ sơ hợp lệ để cập nhật."); const user = await users.updateUser(session.userId, { displayName: displayName(request.body.displayName) }); if (!user) throw new ApiError(404, "USER_NOT_FOUND", "Không tìm thấy người dùng."); return { user: serialize(user) }; });
  app.get("/api/admin/users", async (request) => { requireAdmin(request, secret); return { users: (await users.listUsers()).map(serialize) }; });
  app.patch<{ Params: { id: string }; Body: Record<string, unknown> }>("/api/admin/users/:id", async (request) => { requireAdmin(request, secret); const body = request.body ?? {}; const forbidden = Object.keys(body).filter((field) => !["displayName", "role", "workspaceId"].includes(field)); if (forbidden.length) throw new ApiError(400, "FORBIDDEN_UPDATE_FIELD", "Không được cập nhật field này.", { fields: forbidden.join(", ") }); const update: Partial<Pick<AuthUser, "displayName" | "role" | "workspaceId">> = {}; if ("displayName" in body) update.displayName = displayName(body.displayName); if ("role" in body) { if (body.role !== "admin" && body.role !== "user") throw new ApiError(400, "INVALID_ROLE", "Role không hợp lệ.", { role: "Role chỉ có thể là admin hoặc user." }); update.role = body.role; } if ("workspaceId" in body) { if (typeof body.workspaceId !== "string" || !body.workspaceId.trim() || body.workspaceId.trim().length > 80) throw new ApiError(400, "INVALID_WORKSPACE", "Workspace không hợp lệ."); update.workspaceId = body.workspaceId.trim(); } if (!Object.keys(update).length) throw new ApiError(400, "INVALID_REQUEST", "Không có field người dùng hợp lệ để cập nhật."); const user = await users.updateUser(request.params.id, update); if (!user) throw new ApiError(404, "USER_NOT_FOUND", "Không tìm thấy người dùng."); return { user: serialize(user) }; });
  app.get<{ Querystring: { event?: string; userId?: string; email?: string; resourceType?: string; resourceId?: string; limit?: string } }>("/api/admin/audit-logs", async (request) => { requireAdmin(request, secret); const limit = Math.min(Math.max(Number.parseInt(request.query.limit ?? "50", 10) || 50, 1), 100); const query: Record<string, unknown> = {}; if (request.query.event) query.event = request.query.event; if (request.query.userId) query.userId = request.query.userId; if (request.query.email) query.email = request.query.email.trim().toLowerCase(); if (request.query.resourceType) query["resource.type"] = request.query.resourceType; if (request.query.resourceId) query["resource.id"] = request.query.resourceId; const logs = await mongoose.connection.collection("authauditlogs").find(query).sort({ createdAt: -1 }).limit(limit).toArray(); return { logs: logs.map(({ _id, ...log }) => ({ id: String(_id), ...log })), filters: query, limit }; });
};
