"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { FinanceShell, Metric, vnd, typeClass, typeLabel } from "@/components/finance/FinanceShell";
import { getFinancialSummary, listFinancialTransactions, type FinancialTransaction } from "@/lib/api/financeClient";

type Summary = { totals: { personalSpending: number; debitCashflow: number; creditDebt: number; outstandingReceivable: number }; realMoney: { debitCashflow: number }; credit: { creditDebt: number } };
const monthRange = () => { const now = new Date(); const from = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString().slice(0, 10); return { from, to: now.toISOString().slice(0, 10) }; };
export default function DashboardPage() {
  const [summary, setSummary] = useState<Summary | null>(null); const [rows, setRows] = useState<FinancialTransaction[]>([]); const [error, setError] = useState("");
  useEffect(() => { const { from, to } = monthRange(); void Promise.all([getFinancialSummary(from, to) as Promise<Summary>, listFinancialTransactions(`?from=${from}&to=${to}`)]).then(([s, r]) => { setSummary(s); setRows(r.slice(0, 6)); }).catch(() => setError("Không thể tải tổng quan tài chính.")); }, []);
  return <FinanceShell title="Tổng quan" action={<Link href="/transactions?add=1" className="rounded-lg bg-[#087f83] px-4 py-2.5 font-semibold text-white">+ Thêm giao dịch</Link>}>{error ? <p role="alert" className="mb-4 rounded-lg bg-red-50 p-4 text-red-700">{error}</p> : null}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Tiền thực tế" value={Math.max(0, -(summary?.realMoney?.debitCashflow ?? 0))} tone="positive" hint="DEBIT + CASH + E-WALLET"/><Metric label="Dư nợ tín dụng" value={summary?.totals.creditDebt ?? 0} tone="debt" hint="Không tính vào tiền thực tế"/><Metric label="Chi tiêu cá nhân" value={summary?.totals.personalSpending ?? 0}/><Metric label="Khoản phải thu" value={summary?.totals.outstandingReceivable ?? 0} tone="receivable" hint="Đang chờ hoàn trả"/></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><section className="cc-section p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">Giao dịch gần đây</h2><Link href="/transactions" className="text-sm font-semibold text-[#087f83]">Xem tất cả</Link></div>{rows.length ? <div className="divide-y">{rows.map((row) => <div key={row.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-semibold">{row.note || row.categoryId}</p><p className="text-xs cc-text-muted">{row.transactionDate} · <span className={`rounded px-2 py-0.5 ${typeClass[row.accountType]}`}>{typeLabel[row.accountType]}</span></p></div><p className="font-bold">{vnd(row.amount)}</p></div>)}</div> : <p className="py-10 text-center cc-text-muted">Chưa có giao dịch trong kỳ.</p>}</section><section className="cc-section p-5"><h2 className="text-xl font-bold">Tách dòng tiền</h2><div className="mt-5 space-y-4"><div><div className="flex justify-between text-sm"><span>Debit / Cash / E-wallet</span><strong>{vnd(summary?.totals.debitCashflow ?? 0)}</strong></div><div className="mt-2 h-3 rounded-full bg-cyan-100"><div className="h-3 w-3/5 rounded-full bg-cyan-600" /></div></div><div><div className="flex justify-between text-sm"><span>Credit debt</span><strong className="text-violet-700">{vnd(summary?.totals.creditDebt ?? 0)}</strong></div><div className="mt-2 h-3 rounded-full bg-violet-100"><div className="h-3 w-2/5 rounded-full bg-violet-600" /></div></div></div></section></div></FinanceShell>;
}
